### ISSUE TITLE
Image re-sizing

### ISSUE THREAD

**Issue by joshua028** [joshua028/webcollage#1]
When changing the size of my image using width, it doesn't change the size. For example under the class wc-top-left, and changing width to 80% it is still taking
up 100% of the page and im not sure what the resolve is. Also am wondering how i can make it so that my images go underneath one another, for example i want my
image under class wc-left-side to be below wc-top-left

**Comment by ellysmlly** [comment]
Cool @joshua028 we covered this in your 1:1 with @sehsarah and I. So feel free to write any notes here if you want to remind your future self of anything then you can close this issue now its solved 👍
